name: 五月天介绍页  Mayday Introduction
url: https://Mayday.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "people" page.
roles:
  - key: faculty
    name: 五月天 Mayday
  - key: grad
    name: 团队成员 Team Members
  - key: ugrad
    name: 经纪公司 Brokerage Company
  - key: collab
    name: 圈内好友 Inner Circle Friends


# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: 主页 Home
    link: /
  - title: 音乐作品 Works
    link: /research.html
  - title: 奖项 Awards
    link: /publications.html
